### ISSUE TITLE
Add GraphQL icon

### ISSUE THREAD

**Issue by gugadev** [LaurentTreguier/vscode-simple-icons#19]
Here is a nice SVG GraphQL icon:

<p align="center">
  <img src="https://i.imgur.com/bT76pXZ.png" />
</p>

Available on [Wikipedia](https://en.wikipedia.org/wiki/File:GraphQL_Logo.svg).

Also, do you have time to build a Marko icon? Nunjucks, EJS and Handlebars I think could have the HTML5 icon.

**Comment by LaurentTreguier** [comment]
Marko also has an icon already, so no problem making one. EJS should already have an icon if you use an extension to have EJS syntax highlighting though... This is the case for a lot of languages, and I think I'll move associations from langage IDs to file extensions for some languages to prevent people from not having icons just because they don't have a extension installed.

**Comment by gugadev** [comment]
+1 That's a good idea. Thanks for your time and work.

**Comment by LaurentTreguier** [comment]
![image](https://cloud.githubusercontent.com/assets/7602755/25022528/7d0bd8c2-2096-11e7-9bfd-73cd19b59610.png)
Here is a marko icon based on the logo; more coming soon

**Comment by LaurentTreguier** [comment]
Based on [the nunjucks frontpage](https://mozilla.github.io/nunjucks/):
![image](https://cloud.githubusercontent.com/assets/7602755/25024518/8a3f1eac-209e-11e7-84fb-35ca72dfca4d.png)
