### ISSUE TITLE
Suggestion: Colorful Folder and File Icons

### ISSUE THREAD

**Issue by jacobcupcake** [LaurentTreguier/vscode-simple-icons#2]
You said you were open to suggestions but I couldn't find a way to contact you for a suggestion.

These two have nice looking folders IMO:
- NomoDark for Visaul Studio
- VSCode Icons

**Comment by LaurentTreguier** [comment]
I think Github issues are the way to go for suggestions. I'll try to tweak the folders a bit and come back here with some design attempts

**Comment by LaurentTreguier** [comment]
![folder-grey](https://cloud.githubusercontent.com/assets/7602755/19738027/25537cf8-9bb6-11e6-986f-90a962ee0c96.png)
![folder-brown](https://cloud.githubusercontent.com/assets/7602755/19738028/255a85fc-9bb6-11e6-85b3-98aa48ee9f79.png)
![folder-expanded-grey](https://cloud.githubusercontent.com/assets/7602755/19738029/256084ac-9bb6-11e6-993e-d0287cda3f10.png)
![folder-expanded-brown](https://cloud.githubusercontent.com/assets/7602755/19738026/254d2088-9bb6-11e6-9aaa-04592eb1bdc2.png)
![folder-expanded-grey-2](https://cloud.githubusercontent.com/assets/7602755/19738138/89c8ba86-9bb6-11e6-9117-0b23af2cc82f.png)
![folder-expanded-brown-2](https://cloud.githubusercontent.com/assets/7602755/19738137/89c0015c-9bb6-11e6-86fe-18e3bfc07acd.png)

These are some icons that could replace the older ones.
I'm not sure about changing the color though. The reason I went with gray was to make folders visually less important than files, since they are generally more important than the folders containing them. However I'm willing to try and use some color for specific folders such as `node_modules` and others that are still relevant.

**Comment by jacobcupcake** [comment]
I think people won't have many issues with folders being colourful, it will help people distinguish folders from files even easier IMO. Especially for Windows users because they are use to the yellow folder icon representing a folder. Being able to distinguish folders right away is great for projects with languages that typically have a lot of folders such as C# with ASP.NET. Also, coloured folders just looks sexier. 

On Wed, Oct 26, 2016 at 2:06 PM -0400, "LaurentTreguier" notifications@github.com wrote:

These are some icons that could replace the older ones.

I'm not sure about changing the color though. The reason I went with gray was to make folders visually less important than files, since they are generally more important than the folders containing them. However I'm willing to try and use some color for specific folders such as node_modules and others that are still relevant.

**Comment by LaurentTreguier** [comment]
Even I (not a big Windows user) am used to seeing yellow folders... I've rethought the design for special folders to make them simpler than they currently are (two icons with multiple colors involved).

| Type of folder | Image |
| --- | --- |
| normal | ![folder](https://cloud.githubusercontent.com/assets/7602755/19837875/cd86a71e-9ec3-11e6-9dde-6397f7cef074.png) |
| .dub | ![d-folder](https://cloud.githubusercontent.com/assets/7602755/19837874/cd866308-9ec3-11e6-89b1-41a4e221bae4.png) |
| .git | ![git-folder](https://cloud.githubusercontent.com/assets/7602755/19837876/cd879e94-9ec3-11e6-8884-20bb81d3fb23.png) |
| bower_components | ![bower-folder](https://cloud.githubusercontent.com/assets/7602755/19837879/cd8aa710-9ec3-11e6-9a89-0e55ddeecd92.png) |
| node_modules | ![nodejs-folder](https://cloud.githubusercontent.com/assets/7602755/19837878/cd8a8c8a-9ec3-11e6-9e07-256feef46099.png) |
| source/src | ![source-folder](https://cloud.githubusercontent.com/assets/7602755/19837881/cd9bb8e8-9ec3-11e6-9375-d07a2dea0ab0.png) |
| .vscode | ![vscode-folder](https://cloud.githubusercontent.com/assets/7602755/19837880/cd9ba524-9ec3-11e6-9520-ceae4dafafe5.png) |
| typings | ![typescript-folder](https://cloud.githubusercontent.com/assets/7602755/19837882/cd9f9ff8-9ec3-11e6-9250-2e6fae708d4d.png) |
| build/bin | ![build-folder](https://cloud.githubusercontent.com/assets/7602755/19837877/cd8996a4-9ec3-11e6-8840-72199bdcbf64.png) |

The open folders are probably going to just have the color though.

**Comment by LaurentTreguier** [comment]
@jakinov I've had no comment in this issue for a long while ; and folders are now all colored... Is it ok to close it ?

**Comment by jacobcupcake** [comment]
Go ahead thanks! Looks good.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
