### ISSUE TITLE
TS angular (pipe|directive|..).spec.ts not shown properly

### ISSUE THREAD

**Issue by maxmarkus** [LaurentTreguier/vscode-simple-icons#22]
The orange Angular icon should appear in front of test spec files. 
This works fine for component.spec.ts and service.spec.ts, but not for other derivates like directive.spec.ts, pipe.spec.ts.

**Comment by LaurentTreguier** [comment]
This was intentional since `.spec.ts` could probably be used for any typescript project testing and not necessarily Angular ones. Is there a list of specific `.***.spec.ts` extensions used by Angular or could it really be any `.spec.ts` file ? (in which case I will consider indeed making `.spec.ts` files bear the Angular icon)
I don't know much about Angular, so this is why Angular icon associations in this extension are less than perfect. So if you stumble upon anything else, please do let me know !
