### ISSUE TITLE
CUDA icon

### ISSUE THREAD

**Issue by yaphtes** [LaurentTreguier/vscode-simple-icons#31]
Hello, can you add specific icon for *.cu

**Comment by LaurentTreguier** [comment]
The icon is associated with the `cuda` language id (provided by [this extension](https://marketplace.visualstudio.com/items?itemName=kriegalex.vscode-cudacpp)). Since it's the only Cuda extension for VSCode, I suppose anyone using Cuda will have it installed (and it's hard to imagine a new extension poping up and using a different language id...)
