### ISSUE TITLE
Add support for TailwindCSS config files

### ISSUE THREAD

**Issue by hacknug** [LaurentTreguier/vscode-simple-icons#45]
Should target files named `tailwind.js` with **maybe** an option to specify a different name since its customizable and users can change it if they want.

Here's the SVG code for the logo:
```svg
<svg class="w-8 h-8 lg:w-12 lg:h-12 block" viewBox="0 0 64 64" xmlns="http://www.w3.org/2000/svg">

    <linearGradient x1="0%" y1="0%" y2="100%" id="logoGradient">
        <stop stop-color="#2383AE" offset="0%"></stop>
        <stop stop-color="#6DD7B9" offset="100%"></stop>
    </linearGradient>

    <path d="M13.5 11.1C15.3 3.9 19.8.3 27 .3c10.8 0 12.15 8.1 17.55 9.45 3.6.9 6.75-.45 9.45-4.05-1.8 7.2-6.3 10.8-13.5 10.8-10.8 0-12.15-8.1-17.55-9.45-3.6-.9-6.75.45-9.45 4.05zM0 27.3c1.8-7.2 6.3-10.8 13.5-10.8 10.8 0 12.15 8.1 17.55 9.45 3.6.9 6.75-.45 9.45-4.05-1.8 7.2-6.3 10.8-13.5 10.8-10.8 0-12.15-8.1-17.55-9.45-3.6-.9-6.75.45-9.45 4.05z" fill-rule="evenodd" fill="url(#logoGradient)" transform="translate(5 16)"></path>
    
</svg>
```

**Comment by LaurentTreguier** [comment]
Toggling icons would require a lot of changes; right now everything is set up to produce icons during the extension build time. I've been using bash to easily read and write to files, and since it's not available on a default Windows installation, I'll probably have to rewrite it in JavaScript.
I'll simply add icons for the issues you've opened for now, and I've created #48 specifically for the custom icon associations feature.
